// <auto-generated />
using System;
using Controle.Library.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Controle.Library.Migrations
{
    [DbContext(typeof(ControleContexto))]
    [Migration("20260202001110_CriadoTabelaDeLote")]
    partial class CriadoTabelaDeLote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Controle.Library.Entidades.Gado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Brinco")
                        .HasColumnType("integer")
                        .HasColumnName("brinco");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTimeOffset>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTimeOffset?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_atualizacao");

                    b.Property<DateTimeOffset>("DataUltimaPesagem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_pesagem");

                    b.Property<int>("Finalidade")
                        .HasColumnType("integer")
                        .HasColumnName("finalidade");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    b.Property<int?>("MaeId")
                        .HasColumnType("integer")
                        .HasColumnName("mae_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<int?>("PaiId")
                        .HasColumnType("integer")
                        .HasColumnName("pai_id");

                    b.Property<decimal>("PesoAtual")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peso_atual");

                    b.Property<decimal?>("PesoNascimento")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_nascimento");

                    b.Property<bool>("Prenhez")
                        .HasColumnType("boolean")
                        .HasColumnName("prenhez");

                    b.Property<int>("Raca")
                        .HasColumnType("integer")
                        .HasColumnName("raca");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("Valido")
                        .HasColumnType("boolean")
                        .HasColumnName("valido");

                    b.HasKey("Id")
                        .HasName("pk_gados");

                    b.HasIndex("Brinco")
                        .IsUnique()
                        .HasDatabaseName("ix_gados_brinco")
                        .HasFilter("valido = true");

                    b.HasIndex("LoteId", "Sexo")
                        .HasDatabaseName("ix_gados_lote_id_sexo");

                    b.ToTable("gados", (string)null);
                });

            modelBuilder.Entity("Controle.Library.Entidades.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_maxima");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTimeOffset?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_atualizacao");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observacoes");

                    b.Property<int>("PastoId")
                        .HasColumnType("integer")
                        .HasColumnName("pasto_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_lotes");

                    b.HasIndex("PastoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_lotes_pasto_id_numero");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("Controle.Library.Entidades.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao");

                    b.Property<int>("GadoId")
                        .HasColumnType("integer")
                        .HasColumnName("gado_id");

                    b.Property<int>("LoteDestinoId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_destino_id");

                    b.Property<int>("LoteOrigemId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_origem_id");

                    b.Property<int?>("LoteOrigemId1")
                        .HasColumnType("integer")
                        .HasColumnName("lote_origem_id1");

                    b.Property<decimal?>("PesoNoMomento")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peso_no_momento");

                    b.Property<string>("ResponsavelMovimentacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("responsavel_movimentacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes");

                    b.HasIndex("LoteOrigemId1")
                        .HasDatabaseName("ix_movimentacoes_lote_origem_id1");

                    b.HasIndex("GadoId", "DataMovimentacao")
                        .HasDatabaseName("ix_movimentacoes_gado_id_data_movimentacao");

                    b.HasIndex("LoteDestinoId", "DataMovimentacao")
                        .HasDatabaseName("ix_movimentacoes_lote_destino_id_data");

                    b.HasIndex("LoteOrigemId", "DataMovimentacao")
                        .HasDatabaseName("ix_movimentacoes_lote_origem_id_data");

                    b.ToTable("movimentacoes", (string)null);
                });

            modelBuilder.Entity("Controle.Library.Entidades.Pasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric")
                        .HasColumnName("area");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_maxima");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTimeOffset?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_atualizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observacoes");

                    b.Property<DateTimeOffset?>("ProximaReforma")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_reforma");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TemAguadouro")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_aguadouro");

                    b.Property<bool>("TemCochoSal")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_cocho_sal");

                    b.Property<bool>("TemSombra")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_sombra");

                    b.Property<int>("TipoPasto")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pasto");

                    b.Property<DateTimeOffset?>("UltimaReforma")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_reforma");

                    b.HasKey("Id")
                        .HasName("pk_pastos");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_pastos_nome");

                    b.ToTable("pastos", (string)null);
                });

            modelBuilder.Entity("Controle.Library.Entidades.Tratamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataAplicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aplicacao");

                    b.Property<DateTimeOffset>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTimeOffset?>("DataProximaAplicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_proxima_aplicacao");

                    b.Property<DateTimeOffset?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_atualizacao");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("dose");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fabricante");

                    b.Property<int>("GadoId")
                        .HasColumnType("integer")
                        .HasColumnName("gado_id");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_produto");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observacoes");

                    b.Property<string>("ResponsavelAplicacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("responsavel_aplicacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("TipoAplicacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_aplicacao");

                    b.HasKey("Id")
                        .HasName("pk_tratamentos");

                    b.HasIndex("GadoId", "DataAplicacao")
                        .HasDatabaseName("ix_tratamentos_gado_id_data_aplicacao");

                    b.ToTable("tratamentos", (string)null);
                });

            modelBuilder.Entity("Controle.Library.Entidades.Gado", b =>
                {
                    b.HasOne("Controle.Library.Entidades.Lote", "Lote")
                        .WithMany("Gados")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gados_lotes_lote_id");

                    b.OwnsOne("Controle.Library.Entidades.GadoDadosEntrada", "DadosEntrada", b1 =>
                        {
                            b1.Property<int>("GadoId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Data")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dados_entrada_data");

                            b1.Property<string>("Origem")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("dados_entrada_origem");

                            b1.Property<long?>("ValorCompra")
                                .HasPrecision(18, 4)
                                .HasColumnType("bigint")
                                .HasColumnName("dados_entrada_valor_compra");

                            b1.HasKey("GadoId");

                            b1.ToTable("gados");

                            b1.WithOwner()
                                .HasForeignKey("GadoId")
                                .HasConstraintName("fk_gados_gados_id");
                        });

                    b.OwnsOne("Controle.Library.Entidades.GadoDadosPrenhez", "DadosPrenhez", b1 =>
                        {
                            b1.Property<int>("GadoId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("DataPrevisaoParto")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dados_prenhez_data_previsao_parto");

                            b1.Property<int>("Origem")
                                .HasColumnType("integer")
                                .HasColumnName("dados_prenhez_origem");

                            b1.HasKey("GadoId");

                            b1.ToTable("gados");

                            b1.WithOwner()
                                .HasForeignKey("GadoId")
                                .HasConstraintName("fk_gados_gados_id");
                        });

                    b.OwnsOne("Controle.Library.Entidades.GadoDadosSaida", "DadosSaida", b1 =>
                        {
                            b1.Property<int>("GadoId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Data")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dados_saida_data");

                            b1.Property<string>("Motivo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("dados_saida_motivo");

                            b1.HasKey("GadoId");

                            b1.ToTable("gados");

                            b1.WithOwner()
                                .HasForeignKey("GadoId")
                                .HasConstraintName("fk_gados_gados_id");
                        });

                    b.Navigation("DadosEntrada");

                    b.Navigation("DadosPrenhez");

                    b.Navigation("DadosSaida");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Lote", b =>
                {
                    b.HasOne("Controle.Library.Entidades.Pasto", "Pasto")
                        .WithMany("Lotes")
                        .HasForeignKey("PastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_pastos_pasto_id");

                    b.Navigation("Pasto");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Movimentacao", b =>
                {
                    b.HasOne("Controle.Library.Entidades.Gado", "Gado")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("GadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_gados_gado_id");

                    b.HasOne("Controle.Library.Entidades.Lote", "LoteDestino")
                        .WithMany()
                        .HasForeignKey("LoteOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_lotes_lote_origem_id");

                    b.HasOne("Controle.Library.Entidades.Lote", "LoteOrigem")
                        .WithMany()
                        .HasForeignKey("LoteOrigemId1")
                        .HasConstraintName("fk_movimentacoes_lotes_lote_origem_id1");

                    b.Navigation("Gado");

                    b.Navigation("LoteDestino");

                    b.Navigation("LoteOrigem");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Pasto", b =>
                {
                    b.OwnsOne("Controle.Library.Entidades.DadosAguadouroPasto", "DadosAguadouro", b1 =>
                        {
                            b1.Property<int>("PastoId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("DataUltimaAfericao")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dados_aguadouro_data_ultima_afericao");

                            b1.Property<decimal>("QuantidadeAferida")
                                .HasColumnType("numeric")
                                .HasColumnName("dados_aguadouro_quantidade_aferida");

                            b1.Property<string>("ResponsavelAfericao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("dados_aguadouro_responsavel_afericao");

                            b1.HasKey("PastoId");

                            b1.ToTable("pastos");

                            b1.WithOwner()
                                .HasForeignKey("PastoId")
                                .HasConstraintName("fk_pastos_pastos_id");
                        });

                    b.OwnsOne("Controle.Library.Entidades.DadosCochoSalPasto", "DadosCochoSal", b1 =>
                        {
                            b1.Property<int>("PastoId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("DataUltimaAfericao")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dados_cocho_sal_data_ultima_afericao");

                            b1.Property<decimal>("QuantidadeAferida")
                                .HasColumnType("numeric")
                                .HasColumnName("dados_cocho_sal_quantidade_aferida");

                            b1.Property<string>("ResponsavelAfericao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("dados_cocho_sal_responsavel_afericao");

                            b1.HasKey("PastoId");

                            b1.ToTable("pastos");

                            b1.WithOwner()
                                .HasForeignKey("PastoId")
                                .HasConstraintName("fk_pastos_pastos_id");
                        });

                    b.Navigation("DadosAguadouro");

                    b.Navigation("DadosCochoSal");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Tratamento", b =>
                {
                    b.HasOne("Controle.Library.Entidades.Gado", "Gado")
                        .WithMany("Tratamentos")
                        .HasForeignKey("GadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tratamentos_gados_gado_id");

                    b.Navigation("Gado");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Gado", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("Tratamentos");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Lote", b =>
                {
                    b.Navigation("Gados");
                });

            modelBuilder.Entity("Controle.Library.Entidades.Pasto", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
