services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cerro_verde_controle
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cerro_verde_financeiro
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"